### ISSUE TITLE
Function `insertEdgeTriple` not updating the attribute in DGraph

### ISSUE THREAD

**Issue by fiedlerp** [alx741/graphite#2]
When you try to update edge/arc attribute in DGraph using `insertEdgeTriple` nothing happens.

Try on your own:
```
g1 = fromArcsList [ Arc 'A' 'B' 3]
g2 = insertEdgeTriple ('A', 'B', 5) g1
print $ toArcsList g2 -- [ Arc 'A' 'B' 3]
```

**Comment by alx741** [comment]
Hey, thanks for reporting it. I'm a bit short of time right now... but will try and fix it next week
