### ISSUE TITLE
Use-case coverage for type-safe support for Multigraphs

### ISSUE THREAD

**Issue by Rojods** [alx741/graphite#4]
Although it is possible to construct a Multi(plex)Graph, that is, one that 'accepts' multiple edges between two nodes, with a clever and simple choice of the edge type `e`, it might be profitable to have the types directly model this MultiGraph use-case.

It is an additional implementation effort, but we could compare `graphite` to other popular networking and graphing libraries such as [networkX](https://networkx.org/) and [jgrapht](https://jgrapht.org/) and see that a migrating user would maybe expect specific support for such graph types! 

Therefore I ask if such use-cases are considered in the future or if the "clever" edge type choice is the current choice for tackling them? Having a library such as `graphite` is quite handy for my research and I could contribute the interfaces required plus some default implementations based on my on demand _if_ the use-case _is_ considered :).

**Comment by alx741** [comment]
That was totally something I wanted to have when I first started, but did end up running out of free time and also haven't been working much with networks lately.

I would love to have that in this library, and pull request are very welcome if you'd like to take give it a go. If it comes in useful for your research then it sounds like something that would be great to have for the ecosystem in general :)

**Comment by Rojods** [comment]
Good to know I can contribute :)! 

At the moment I'm seeing the (sadly few) graphs and networking packages that one can find in HackageDB as to minimize the amount of work I have to do in order to get some research results, since my topic is not really networks, but (sort of) compilers! 

In case it is indeed worth it to spend some time in the supporting libraries for my project, i'd be more than happy to contribute it with a pull request! I think we can close the issue as well since your answer nails it :).
